### ISSUE TITLE
Deal with co-sponsors issue

### ISSUE THREAD

**Issue by eafurlan** [eafurlan/cs373-idb#29]
Options:
-make cosponsors text, not links
-scrape everything

(Both Arman and Brian planned to work on this; only one assignee is allowed though!)

**Comment by b-hodge** [comment]
We're just scraping everything, so all links will be active

**Comment by chareth** [comment]
pass list of bills to legislator in views.py
pass list of legislators to bill in views.py

**Comment by abaratif** [comment]
Brian has pulled all data and it is now in prod database
